## A. Loading Dataset from ScikitLearn

### Step 1
Load `iris` dataset from ScikitLearn using `load_iris()`. Assign the dataset to `X` and the target values to `y`.

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
X,y = iris.data, iris.target

### Step 2
Print the dataset keys using `iris_dataset.keys()`

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

### Step 3
Print the names of the categories in the target file

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### Step 4
Print the feature names in the Iris dataset

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

### Step 5
Print the type of the Iris dataset.

In [44]:
type(X)

numpy.ndarray

In [45]:
type(iris)

sklearn.utils._bunch.Bunch

### Step 6
Print the shape of the Iris dataset.

In [10]:
X.shape

(150, 4)

### Step 7
Print the first five rows of the Iris dataset.

In [25]:
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Step 8
Print the type of the target variable of Iris dataset.

In [22]:
type(y)

numpy.ndarray

### Step 9
Print the shape of the target variable of Iris dataset.

In [23]:
y.shape

(150,)

### Step 10
Print the entire target variable values of the Iris dataset.

In [24]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### Step 11
Import numpy with `import numpy as np` and use the `numpy.unique()` function to print the unique values of the target variable of Iris dataset

In [26]:
import numpy as np
np.unique(y)

array([0, 1, 2])

### Step 12
Split dataset into train and test datasets using `from sklearn.model_selection import train_test_split`

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,random_state=42, stratify=y)

### Step 13
Print the shape of train/test datasets and the train/test target variables.

In [30]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(112, 4)
(38, 4)
(112,)
(38,)


### Step 14
Build your K-neighbors classifier for nearest neighbor of 1 using `from sklearn.neighbors import KNeighborsClassifier`, fit the model to your train dataset and make a prediction for teh data point of `[5, 1.9, 1, 0.2]`. Print your prediction class value as an integer and also the corresponding string label.

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
knn = KNeighborsClassifier(n_neighbors = 1)

In [38]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [39]:
new_data_point = [[5, 1.9, 1, 0.2]]

In [40]:
prediction = knn.predict(new_data_point)

In [41]:
predicted_label = iris.target_names[prediction]

In [43]:
print("Predicted class (integer):", prediction)
print("Predicted class (string label):", predicted_label)

Predicted class (integer): [0]
Predicted class (string label): ['setosa']
